on:
  workflow_dispatch:

jobs:
  compile_idris:
    name: Formal verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.3.0
    
    - name: Install Brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    - name: Install Idris
      run: /home/linuxbrew/.linuxbrew/bin/brew install idris2
    
    - name: Search for Idris (to speed up trial-and-failure loop)
      run: |
        echo $PATH
        find /home/linuxbrew/ -name "*idris2*"
    
    - name: Compile formal description
      run: idris2 freelance-highlevel.idr -o contracts-fd
    
    - name: Test executable
      run: ./contracts-fd
    
