on:
  workflow_dispatch:

jobs:
  compile_idris:
    name: Formal verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.3.0
    
    - name: Install Brew
      run: sudo apt-get install linuxbrew-wrapper
    
    - name: Install Idris
      run: brew install idris2
    
    - name: Compile formal description
      run: idris freelance-highlevel.idr -o contracts-fd
    
    - name: Test executable
      run: ./contracts-fd
    
