on:
  workflow_dispatch:

jobs:
  compile_idris:
    name: Formal verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Cabal
    - uses: actions/checkout@v3
    - run: sudo apt-get install cabal-install make
    - run: cabal update
    
    - name: Install Idris
    - uses: actions/checkout@v3
    - run: cabal install idris
    
    - name: Compile formal description
    - uses: actions/checkout@v3
    - run: idris freelance-highlevel.idr -o contracts-fd
    
    - name: Test executable
    - uses: actions/checkout@v3
    - run: ./contracts-fd
    
